var Socket=Socket {
  nsp: Namespace {
    name: '/',
    server: Server {
      nsps: [Object],
      parentNsps: Map {},
      _path: '/socket.io',
      _serveClient: true,
      parser: [Object],
      encoder: Encoder {},
      _adapter: [Function: Adapter],
      _origins: '*:*',
      sockets: [Circular],
      eio: [Server],
      httpServer: [Server],
      engine: [Server]
    },
    sockets: { CxAbgSCyrS_Pt05fAAAA: [Circular] },  
    connected: { CxAbgSCyrS_Pt05fAAAA: [Circular] },
    fns: [],
    ids: 0,
    rooms: [],
    flags: {},
    adapter: Adapter {
      nsp: [Circular],
      rooms: [Object],
      sids: [Object],
      encoder: Encoder {}
    },
    _events: [Object: null prototype] { connection: [Function] },
    _eventsCount: 1
  },
  server: Server {
    nsps: { '/': [Namespace] },
    parentNsps: Map {},
    _path: '/socket.io',
    _serveClient: true,
    parser: {
      protocol: 4,
      types: [Array],
      CONNECT: 0,
      DISCONNECT: 1,
      EVENT: 2,
      ACK: 3,
      ERROR: 4,
      BINARY_EVENT: 5,
      BINARY_ACK: 6,
      Encoder: [Function: Encoder],
      Decoder: [Function: Decoder]
    },
    encoder: Encoder {},
    _adapter: [Function: Adapter],
    _origins: '*:*',
    sockets: Namespace {
      name: '/',
      server: [Circular],
      sockets: [Object],
      connected: [Object],
      fns: [],
      ids: 0,
      rooms: [],
      flags: {},
      adapter: [Adapter],
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    eio: Server {
      clients: [Object],
      clientsCount: 1,
      wsEngine: 'ws',
      pingTimeout: 5000,
      pingInterval: 25000,
      upgradeTimeout: 10000,
      maxHttpBufferSize: 100000000,
      transports: [Array],
      allowUpgrades: true,
      allowRequest: [Function: bound ],
      cookie: 'io',
      cookiePath: '/',
      cookieHttpOnly: true,
      perMessageDeflate: [Object],
      httpCompression: [Object],
      initialPacket: [Array],
      ws: [WebSocketServer],
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    httpServer: Server {
      insecureHTTPParser: undefined,
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _connections: 1,
      _handle: [TCP],
      _usingWorkers: false,
      _workers: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      keepAliveTimeout: 5000,
      maxHeadersCount: null,
      headersTimeout: 40000,
      _connectionKey: '6::::5000',
      [Symbol(IncomingMessage)]: [Function: IncomingMessage], 
      [Symbol(ServerResponse)]: [Function: ServerResponse],   
      [Symbol(kCapture)]: false,
      [Symbol(asyncId)]: 6
    },
    engine: Server {
      clients: [Object],
      clientsCount: 1,
      wsEngine: 'ws',
      pingTimeout: 5000,
      pingInterval: 25000,
      upgradeTimeout: 10000,
      maxHttpBufferSize: 100000000,
      transports: [Array],
      allowUpgrades: true,
      allowRequest: [Function: bound ],
      cookie: 'io',
      cookiePath: '/',
      cookieHttpOnly: true,
      perMessageDeflate: [Object],
      httpCompression: [Object],
      initialPacket: [Array],
      ws: [WebSocketServer],
      _events: [Object: null prototype],
      _eventsCount: 1
    }
  },
  adapter: Adapter {
    nsp: Namespace {
      name: '/',
      server: [Server],
      sockets: [Object],
      connected: [Object],
      fns: [],
      ids: 0,
      rooms: [],
      flags: {},
      adapter: [Circular],
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    rooms: { CxAbgSCyrS_Pt05fAAAA: [Room] },
    sids: { CxAbgSCyrS_Pt05fAAAA: [Object] },
    encoder: Encoder {}
  },
  id: 'CxAbgSCyrS_Pt05fAAAA',
  client: Client {
    server: Server {
      nsps: [Object],
      parentNsps: Map {},
      _path: '/socket.io',
      _serveClient: true,
      parser: [Object],
      encoder: Encoder {},
      _adapter: [Function: Adapter],
      _origins: '*:*',
      sockets: [Namespace],
      eio: [Server],
      httpServer: [Server],
      engine: [Server]
    },
    conn: Socket {
      id: 'CxAbgSCyrS_Pt05fAAAA',
      server: [Server],
      upgrading: false,
      upgraded: false,
      readyState: 'open',
      writeBuffer: [],
      packetsFn: [],
      sentCallbackFn: [],
      cleanupFn: [Array],
      request: [IncomingMessage],
      remoteAddress: '::1',
      checkIntervalTimer: null,
      upgradeTimeoutTimer: null,
      pingTimeoutTimer: Timeout {
        _idleTimeout: 30000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 3026,
        _onTimeout: [Function],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: true,
        [Symbol(asyncId)]: 16,
        [Symbol(triggerId)]: 12
      },
      transport: [XHR],
      _events: [Object: null prototype],
      _eventsCount: 3
    },
    encoder: Encoder {},
    decoder: Decoder { reconstructor: null, _callbacks: [Object] },
    id: 'CxAbgSCyrS_Pt05fAAAA',
    request: IncomingMessage {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      socket: [Socket],
      connection: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '/socket.io/?EIO=3&transport=polling&t=NGDtWeQ',   
      method: 'GET',
      statusCode: null,
      statusMessage: null,
      client: [Socket],
      _consuming: false,
      _dumped: true,
      _query: [Object: null prototype],
      res: [ServerResponse],
      cleanup: [Function: cleanup],
      [Symbol(kCapture)]: false
    },
    onclose: [Function: bound ],
    ondata: [Function: bound ],
    onerror: [Function: bound ],
    ondecoded: [Function: bound ],
    sockets: { CxAbgSCyrS_Pt05fAAAA: [Circular] },
    nsps: { '/': [Circular] },
    connectBuffer: []
  },
  conn: Socket {
    id: 'CxAbgSCyrS_Pt05fAAAA',
    server: Server {
      clients: [Object],
      clientsCount: 1,
      wsEngine: 'ws',
      pingTimeout: 5000,
      pingInterval: 25000,
      upgradeTimeout: 10000,
      maxHttpBufferSize: 100000000,
      transports: [Array],
      allowUpgrades: true,
      allowRequest: [Function: bound ],
      cookie: 'io',
      cookiePath: '/',
      cookieHttpOnly: true,
      perMessageDeflate: [Object],
      httpCompression: [Object],
      initialPacket: [Array],
      ws: [WebSocketServer],
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    upgrading: false,
    upgraded: false,
    readyState: 'open',
    writeBuffer: [],
    packetsFn: [],
    sentCallbackFn: [],
    cleanupFn: [ [Function], [Function] ],
    request: IncomingMessage {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      socket: [Socket],
      connection: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '/socket.io/?EIO=3&transport=polling&t=NGDtWeQ',   
      method: 'GET',
      statusCode: null,
      statusMessage: null,
      client: [Socket],
      _consuming: false,
      _dumped: true,
      _query: [Object: null prototype],
      res: [ServerResponse],
      cleanup: [Function: cleanup],
      [Symbol(kCapture)]: false
    },
    remoteAddress: '::1',
    checkIntervalTimer: null,
    upgradeTimeoutTimer: null,
    pingTimeoutTimer: Timeout {
      _idleTimeout: 30000,
      _idlePrev: [TimersList],
      _idleNext: [TimersList],
      _idleStart: 3026,
      _onTimeout: [Function],
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: false,
      [Symbol(refed)]: true,
      [Symbol(asyncId)]: 16,
      [Symbol(triggerId)]: 12
    },
    transport: XHR {
      readyState: 'open',
      discarded: false,
      closeTimeout: 30000,
      maxHttpBufferSize: 100000000,
      httpCompression: [Object],
      supportsBinary: true,
      _events: [Object: null prototype],
      _eventsCount: 5,
      sid: 'CxAbgSCyrS_Pt05fAAAA',
      req: null,
      res: null,
      writable: false
    },
    _events: [Object: null prototype] {
      close: [Array],
      data: [Function: bound ],
      error: [Function: bound ]
    },
    _eventsCount: 3
  },
  rooms: {},
  acks: {},
  connected: true,
  disconnected: false,
  handshake: {
    headers: {
      host: 'localhost:5000',
      connection: 'keep-alive',
      accept: '*/*',
      origin: 'http://localhost',
      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
      referer: 'http://localhost/',
      'accept-encoding': 'gzip, deflate, br',
      'accept-language': 'es-ES,es;q=0.9',
      cookie: 'io=f3eZ2Uem3pgjwKhMAAAA'
    },
    time: 'Thu Aug 20 2020 18:54:51 GMT-0300 (GMT-03:00)',    
    address: '::1',
    xdomain: true,
    secure: false,
    issued: 1597960491823,
    url: '/socket.io/?EIO=3&transport=polling&t=NGDtWeQ',     
    query: { EIO: '3', transport: 'polling', t: 'NGDtWeQ' }   
  },
  fns: [],
  flags: {},
  _rooms: []
}